# Generated by Django 2.2 on 2019-04-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BraFitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bra_size', models.CharField(blank=True, max_length=10, null=True)),
                ('band_measurement', models.DecimalField(decimal_places=2, help_text='Enter in inches measurment under bust', max_digits=5)),
                ('band_size', models.IntegerField(blank=True)),
                ('bust_measurement', models.DecimalField(decimal_places=2, help_text='Enter measurement in inches for bust', max_digits=5)),
                ('cup_size', models.CharField(blank=True, max_length=10)),
                ('bust_circumference', models.BooleanField(blank=True, default=False, help_text='Did you measure all the way around? That is ok! Just click here')),
                ('currently_wearing', models.CharField(choices=[('None', 'None'), ('Sports', 'Sports'), ('Bralette', 'Bralette'), ('PushUp', 'Push-Up'), ('LightlyLined', 'Lightly-Lined')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
