# Generated by Django 2.2 on 2019-04-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190417_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brafitting',
            options={'ordering': ['date_sized']},
        ),
        migrations.AddField(
            model_name='brafitting',
            name='date_sized',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of Bra Fitting'),
        ),
    ]
