# Generated by Django 2.2 on 2019-04-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190417_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brafitting',
            name='currently_wearing',
            field=models.CharField(choices=[('None', 'None'), ('SportsBra', 'Sports Bra'), ('Bralette', 'Bralette'), ('PushUp', 'Push-Up'), ('LightlyLined', 'Lightly-Lined')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='breast_symmetry',
            field=models.BooleanField(blank=True, default=True, verbose_name='Symmetry'),
        ),
    ]
