# Generated by Django 2.2 on 2019-04-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='breast_tissue',
            new_name='breast_shape',
        ),
    ]
