# Generated by Django 2.2 on 2019-04-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190420_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='ur',
            new_name='url',
        ),
    ]
