# Generated by Django 2.2 on 2019-04-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190420_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='breast_symmetry',
        ),
    ]
