# Generated by Django 2.2 on 2019-04-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_suggestion_breast_symmetry'),
        ('core', '0005_auto_20190420_1019'),
    ]

    operations = [
    ]
