# Generated by Django 2.2 on 2019-04-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20190420_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='site_user',
        ),
        migrations.RemoveField(
            model_name='brafitting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.AddField(
            model_name='brafitting',
            name='fitting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='fitting_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.BraFitting'),
        ),
    ]
