# Generated by Django 2.2 on 2019-04-21 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190421_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brafitting',
            name='fitting_user',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fitting_session',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.BraFitting'),
            preserve_default=False,
        ),
    ]
