# Generated by Django 2.2 on 2019-04-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190424_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brafitting',
            name='bust_circumference',
            field=models.CharField(choices=[('Half', 'Half Way Around'), ('AllWay', 'All The Way Around')], default='Half', max_length=25),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='bra_wire',
            field=models.CharField(choices=[('Underwire', 'Underwire'), ('Wireless', 'Wireless')], default='Underwire', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='breast_placement',
            field=models.CharField(choices=[('Near', 'Near'), ('Far', 'Far')], default='Near', max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='breast_shape',
            field=models.CharField(choices=[('Teardrop', 'Teardrop'), ('Round', 'Round'), ('None', 'Other')], default='None', max_length=30),
        ),
    ]
