# Generated by Django 2.2 on 2019-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190425_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category_type',
            field=models.CharField(default='All', max_length=100),
        ),
    ]
