# Generated by Django 2.2 on 2019-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190428_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='breast_shape',
            field=models.CharField(choices=[('Teardrop', 'Teardrop'), ('Round', 'Round'), ('None', 'Neither Teardrop nor Round')], default='None', max_length=30),
        ),
    ]
