# Generated by Django 2.2 on 2019-05-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190429_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brafitting',
            options={'ordering': ['-date_sized']},
        ),
    ]
